# -*- coding: utf-8 -*-
"""day-2_DEandGenAi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WtoTmPXzm7u9p19i0poSPBvzuXJG3fdK
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings("ignore")
print("Sucessfully imported libraries")

import pandas as pd

df=pd.read_csv('/content/student_performance.csv')
display(df.head(3))

# Define a helper function to run SQL queries and display results
def run_query(sql_query, description):
    """
    Executes a given SQL query using the global 'conn' object
    and returns the result as a pandas DataFrame.
    Prints a description before executing the query.
    """
    print(description)
    try:
        # 'conn' (sqlite connection object) is expected to be globally available from a previous cell.
        result_df = pd.read_sql_query(sql_query, conn)
        return result_df
    except NameError:
        print("Error: 'conn' object (SQLite connection) not found. Please ensure the database connection cell is executed.")
        return None
    except Exception as e:
        print(f"Error executing query: {e}")
        return None

print(f"Dataset loaded: {df.shape[0]} students, {df.shape[1]} columns")
print(f"")

conn=sqlite3.connect('college.db')
cursor=conn.cursor()
print("Cursor created")

df.to_sql(
    'students',
    conn,
    if_exists='replace',
    index=False
)

cursor.execute('SELECT COUNT(*) FROM students')
count=cursor.fetchone()[0]
print(f"Number of students in the database: {count}")

cursor.execute("PRAGMA table_info(students)")
columns_info=cursor.fetchall()

print("Table Structure of 'students':")
print(f"{'Column Name' :<25} {'Data Type':<12}")
print("-"*38)
for col in columns_info:
    print(f"{col[1]:<25} {col[2]:<12}")

sql_query = "SELECT * FROM students ORDER BY student_id DESC LIMIT 5"
description = "Last 5 entries in the 'students' table:"
result = run_query(sql_query, description)
display(result)

query_top_math_score = """
SELECT name, department, math_score
FROM students
ORDER BY math_score DESC
LIMIT 5
"""
description_top_math_score = "Top 5 students with the highest math scores:"
result_top_math_score = run_query(query_top_math_score, description_top_math_score)
display(result_top_math_score)

student_highest_programming_query = """SELECT name, department, programming_score
                                   FROM students
                                   ORDER BY programming_score DESC
                                   LIMIT 5"""
result_highest_student = run_query(student_highest_programming_query, description="Student with the highest programming score:")
display(result_highest_student)

query5="""SELECT name, department, attendance_percentage
          From students
          where attendance_percentage > 90
          AND department!='Civil'
          Order By attendance_percentage DESC
          """
attdancehigh = run_query(query5, description="Student with the highest Attdance score:")
display(attdancehigh)

dept_data ={
    'dept_code' : ['CS','EC','ME','CIV'],
    'dept_name' : ['Computer Science','Electronics','Mechanical','Civil'],
    'hod_name' : ['Dr. A','Dr. B','Dr. C','Dr. D'],
    'established': [1985,1999,2006,2008],
    'intake': [60,60,69,37]
}

dept_data = pd.DataFrame(dept_data)
print(dept_data)

# Create a mapping from 'department' name to 'dept_code'
department_to_code_map = dict(zip(dept_data['dept_name'], dept_data['dept_code']))

# Apply the mapping to create a new 'dept_code' column in df
df['dept_code'] = df['department'].map(department_to_code_map)

# Store the department data in the SQLite database
dept_data.to_sql(
    'department',
    conn,
    if_exists='replace',
    index=False
)

# Recreate the 'students' table with the new 'dept_code' column
df.to_sql(
    'students',
    conn,
    if_exists='replace',
    index=False
)

print("\n'dept_code' column added to student DataFrame and 'department' and 'students' tables updated in database.")

query_join="""
 SELECT s.name,s.math_score,d.dept_name,d.hod_name,d.established
 FROM students AS s INNER JOIN department AS d
 ON s.dept_code=d.dept_code
 ORDER BY s.math_score DESC LIMIT 8 """
result_join = run_query(query_join, description="Students with their department details:")
display(result_join)

chart_sql="""
SELECT department,ROUND(AVG(math_score),2) AS avg_math
FROM students
GROUP BY department
ORDER BY avg_math DESC
"""
chart1_data = pd.read_sql_query(chart_sql, conn)
fig,ax=plt.subplots(figsize=(10,6))
ax.bar(chart1_data['department'],chart1_data['avg_math'])
ax.set_xlabel('Department')
ax.set_ylabel('Average Math Score')
ax.set_title('Average Math Score by Department')
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
plt.hist(df['math_score'], bins=10, edgecolor='black')
plt.xlabel('Math Score')
plt.ylabel('Number of Students')
plt.title('Distribution of Math Scores')
plt.grid(axis='y', alpha=0.75)
plt.tight_layout()
plt.show()

