# -*- coding: utf-8 -*-
"""day-3_DEandGenAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1diaaXlP-7fipd5bL8Y8WEagYvhlgE0YQ
"""

import pandas as pd
import requests
import json
import matplotlib.pyplot as plt

import matplotlib.patches as mpatches
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

print(" Libraries imported successfully.")
print(f" pandas version: {pd.__version__}")
print(f" requests version: {requests.__version__}")
print(f" json version: {json.__version__}")
print(f" Loaded at : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")







raw_df=pd.read_csv('messy_sales_data.csv')
print(f"Rows            : {raw_df.shape[0]}")
print(f"Columns         : {raw_df.shape[1]}")
print(f"column names    : {raw_df.columns.tolist()}")
print("\n First 5v row :\n")
raw_df.head()

print("\n[1] Missing values")
print(raw_df.isnull().sum())
print(f"\n[2] Duplicate Rows: {raw_df.duplicated().sum()}")
print("\n[3] Data types")
print(raw_df.dtypes)
print("\n[4] Unique Categories:",raw_df['category'].dropna().unique().tolist())
print("[4] Sample order dates:",raw_df['order_date'].unique()[:8].tolist())
print("[4] Sample name:",raw_df['customer_name'].dropna().unique()[:8].tolist())

df=raw_df.copy()
print(f"working copy created with shape : {df.shape}")
print("raw_df is untouched. We can always reset with: df=raw_df.copy()")

print(f"Total missing values  before fix:{df.isnull().sum().sum()}")
df['customer_name'].fillna('unknown Customer', inplace=True)
median_qty=df['quantity'].median()
df['quantity'].fillna(median_qty,inplace=True)
print(f"filled missing quantity:{median_qty}")
df['category'].fillna('Uncategorized',inplace=True)
print(f"Total missing values  after fix:{df.isnull().sum().sum()}")

df['product'].fillna('Unknown Product', inplace=True)
print(f"Total missing values after fixing product: {df.isnull().sum().sum()}")
df.head(30)

"""With all missing values handled, let's now ensure that all columns have the correct data types. Based on the `df.info()` output, 'order_date' is currently an object and should be converted to datetime. 'unit_price' and 'quantity' are appropriate, and 'order_id' could be converted to string if not used for numerical operations."""

print(f"Duplicated rows : {df.duplicated().sum()}")

print(f"Rows before duplication: {len(df)}")
print(f"Duplicate rows found    : {df.duplicated().sum()}")
duplicate_mask=df.duplicated(keep=False)
print("\nThe duplicate rows are: ")
print(df[duplicate_mask][['order_id','customer_name','product','order_date']].to_string(index=True))
df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)
print(f"\nRows after duplication: {len(df)}")
print(f"Rows removed            :{len(raw_df)-len(df)}")

print("Smaple adted before parsing :")
print(df['order_date'].head(10).tolist())
df['order_date']=pd.to_datetime(df['order_date'],dayfirst=False,errors='coerce')
nat_mask=df['order_date'].isnull()
df.loc[nat_mask,'order_date']=pd.to_datetime(
    raw_df.loc[nat_mask,'order_date'],dayfirst=True,errors='coerce')
nat_count=df['order_date'].isnull().sum()
print(f"\nUnparsable dates found: {nat_count}")
df['year']=df['order_date'].dt.year
df['month']=df['order_date'].dt.month
df['month_name']=df['order_date'].dt.strftime('%B')
df['day_name']=df['order_date'].dt.strftime('%A')
print("\nSample dated after parsing :")
print(df[['order_date','year','month','month_name','day_name']].head(8))

print("Names Before standardization (sample):")
print(df['customer_name'].unique()[:8].tolist())
df['customer_name']=df['customer_name'].str.strip().str.title()
print("\nNames After standardization (sample):")
print(df['customer_name'].unique()[:8].tolist())

wrong_mask=(df['product']=='keyboard')&(df['category']=='Electronics')
print(f"Rows to fix: {wrong_mask.sum()}")
print("Before fix")
print(df[wrong_mask][['order_id','product','category']].to_string(index=False))
df.loc[wrong_mask,'category']='Accessories'
print("\nAfter fix")
print(df[wrong_mask][['order_id','product','category']].to_string(index=False))

df['quantity']=pd.to_numeric(df['quantity'],errors='coerce').astype(int)
df['unit_price']=pd.to_numeric(df['unit_price'],errors='coerce')

df['revenue']=df['quantity']*df['unit_price']
print("Revenue column created successfully.")
print("\nSample: quantity x unit_price = revenue")
print(df[['customer_name','product','quantity','unit_price','revenue']].head(8).to_string(index=False))

output_filename='clean_sales_data.csv'
df.to_csv(output_filename,index=False)

print(f"Cleaned data saved to: {output_filename}")
print(f"FInal dataset: {df.shape[0]} rows x {df.shape[1]} columns")

SERP_API_KEY='bff26cdf888abd3b98f6621bb43364f6b13232e0e8fd75585f86353d3e8e84fe'
SERP_URL='https://serpapi.com/search.json'

SEARCH_QUERY='DATA ENGINEER INDIA'
print(f"SerpAPI Key  : {'Set (live data)' if SERP_API_KEY != 'YOUR_SERPAPI_KEY_HERE' else 'Not set (fallback data will be used)'}")
print(f"Search query : {SEARCH_QUERY}")

import requests

def fetch_jobs(query, api_key, num_pages=2):
    """
    Fetches job listings from Google Jobs via SerpAPI.


    Parameters:
        query    (str) : The job search query (e.g. 'Data Engineer India')
        api_key  (str) : Your SerpAPI key
        num_pages(int) : Number of result pages to fetch (default: 2)


    Returns:
        list : A list of job dictionaries
    """
    all_jobs = []


    for page in range(num_pages):
        # API pagination: 'start' tells the API which result to start from
        # Page 0: results 0-9, Page 1: results 10-19, etc.
        params = {
            'engine'    : 'google_jobs',  # Use the Google Jobs search engine
            'q'         : query,
            'api_key'   : api_key,
            'hl'        : 'en',           # Language: English
            'start'     : page * 10       # Pagination offset
        }


        try:
            response = requests.get(SERP_URL, params=params, timeout=15)


            if response.status_code == 200:
                data = response.json()


                # 'jobs_results' is the key in the JSON that holds the job listings
                jobs = data.get('jobs_results', [])


                for job in jobs:
                    # Extract and normalize each job's fields
                    # .get('key', 'default') returns the value if the key exists,
                    # or 'default' if it does not — prevents KeyError crashes
                    all_jobs.append({
                        'title'      : job.get('title', 'Unknown Title'),
                        'company'    : job.get('company_name', 'Unknown Company'),
                        'location'   : job.get('location', 'Unknown Location'),
                        'posted'     : job.get('detected_extensions', {}).get('posted_at', 'Unknown'),
                        'salary'     : job.get('detected_extensions', {}).get('salary', 'Not Disclosed'),
                        'job_type'   : job.get('detected_extensions', {}).get('schedule_type', 'Not Specified'),
                        'description': job.get('description', '')[:300]  # First 300 characters only
                    })


                print(f"  Page {page + 1}: fetched {len(jobs)} jobs")
            else:
                print(f"  Page {page + 1}: API error {response.status_code}")


        except Exception as e:
            print(f"  Page {page + 1}: error — {e}")


    return all_jobs


# ── Actually call the function ────────────────────────────────
job_records = []


if SERP_API_KEY != 'YOUR_SERPAPI_KEY_HERE':
    print(f"Fetching job listings for: '{SEARCH_QUERY}'")
    job_records = fetch_jobs(SEARCH_QUERY, SERP_API_KEY)
    print(f"Total jobs fetched: {len(job_records)}")
else:
    print("No SerpAPI key provided — fallback job data will be loaded next.")

